Feature/#30 Scrap
ChatCode9/ChatCode-backend pull request #38
Opened 2024-05-17 06:50 UTC by eunzz6

## 🚀 Related Issues
> #30 
## 🛠️ Summary
> 게시물을 스크랩하고, 스크랩 목록을 조회하고, 삭제할 수 있습니다.
## 💬 Review Requirements
> 파일이 잘못 업로드되어 pr 재업로드 합니다 !
   스웨거도 활용해 보았습니다 ! 테스트코드 작성이 미숙해서 Postman으로 테스트 하였습니다 😅
   테스트코드도 열심히 공부해보겠습니다

2024-05-17 08:02 UTC, NaMooJoon requested changes
스크랩 기능 고생하셨습니다!! 
몇몇 리뷰에서 코드 스타일 관련해서 제 개인 의견 달아드렸는데, 제 개인 개인적인 의견일 뿐이니 더 괜찮은 방법이 있다면 제안해주세요 😚

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    }
DTO로도 articleId를 받고 있는데, Path에서도 articleId를 받고 있네요! 안쓰는 건 지우는 게 좋을 것 같습니다.

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/controller/ScrapController.java
> +//import com.chatcode.dto.avatar.AvatarResponse;
안쓰는 주석이라면 지워주시면 좋을 것 같습니다 ~!!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    }
그리고 DTO안에 특정 유저에 스크랩을 추가하는 기능을 본인만 접근 가능하도록 제한하실 생각이라면, 
JWT 토큰 인증을 통해 얻은 LoginUser 정보로 이용하는 것도 좋을 듯 합니다!!

그렇게 하시면 requestDto를 없이도 request 처리 하실 수 있을 것 같아요 ~!!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    @DeleteMapping("/{avatarId}/{articleId}")
저도 rest api를 공부 중이라 확실치는 않지만!!! (저희 민제님한테 여쭤보시죠 ㅎㅎ)

사용자 리소스를 다루는 API의 경우
`/avatars/{avatarId}/scrap/{articleId}`처럼 각각 URL에 담긴 아이디 값이 어떤 것을 의미하는지 알 수 있게 하는 것이 좀 더 좋을 듯 합니다!!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    private Article articleId;
`@JoinColumn` 어노테이션으로 이미 avatar_id라고 명시해주셨기 때문에, 필드 이름은 엔티티이니 avatar, article을 사용하시는 게 좋을 듯 합니다.

그리고 괜찮으시다면 JPA FetchType 한번 찾아보시고, 어느 전략을 가져갈 건지도 명시해주시면 좋을 것 같아요 !

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    private LocalDateTime dateCreated;
JPA에서 `@CreatedDate`와 `@DateTimeFormat`를 한번 찾아보시고 이용해주시면 좋을 것 같습니다!!

> AuditingFields 를 참고하셔도 좋을 것 같아요!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    @Column(nullable = false, columnDefinition = "BIGINT default 0")
columnDefinition은 createTable.sql에서 수정해주세요!!
아마 Dev 모드에서 JPA가 create 모드가 아니라서 해당 사항이 적용이 안될 것 같아요 ㅠㅠ

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/domain/entity/scrap/ScrapId.java
> +}
개인적으로 JPA 복합키 선언을 inner class로 선언하는 게 좀 더 깔끔한 것 같습니다만, 은정님 의견은 어떠실까요!!!!!😎

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/dto/scrap/ScrapResponseDTO.java
> +    private LocalDateTime dateCreated;
description 깔끔합니다 ~👍

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/repository/scrap/ScrapReadRepository.java
> +        return em.createQuery("SELECT s FROM Scrap s WHERE s.avatarId.id = :avatarId AND s.articleId.id = :articleId", Scrap.class)
이렇게 직접 쿼리를 날릴 수 있군요!! 👀
하나 배워가요!!!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +        LocalDateTime now = LocalDateTime.now();
요고는 JPA @CreatedDate 사용하면 지워주셔도 될 것 같아요!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Avatar avatar = optionalAvatar.orElseThrow(() -> new ContentNotFoundException("Avatar not found"));
```suggestion
        Avatar avatar = avatarReadRepository.findById(scrapRequestDTO.getAvatarId())
                        .orElseThrow(() -> new ContentNotFoundException("Avatar not found"));
```
Optional은 요롷게 사용도 할 수 있습니다!!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Article article = optionalArticle.get();
여기도 한줄로 줄일 수 있습니다!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +        }
null값 체킹은 컨트롤러 단에서 @Valid 어노테이션을 사용해서 검증하는 게 어떨까 싶습니다 !

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +                    Article article = optionalArticle.get();
여기도 피드백 드린 Optional로 코드 줄이면 가독성 더 좋을 것 같아요!

2024-05-17 08:02 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +                })
저는 개인적으로 Entity -> DTO 같은 케이스는 생성자(또는 정적 메서드)의 파라미터에 entity 자체를 넘겨주는 걸 선호하는 편입니다!!
혹시 아직 선호하시는 스타일이 없으시다면, 민제님 코드랑 제 코드에서 Entity to DTO, DTO to Entity를 어떻게 변환하는 지 확인해보시면 좋을 것 같아요 !

2024-05-17 08:21 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +//import com.chatcode.dto.avatar.AvatarResponse;
넵!!

2024-05-17 08:23 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    @DeleteMapping("/{avatarId}/{articleId}")
엇 준현님 말씀대로 아바타페이지에서 스크랩목록을 조회하고 삭제하는게 맞을 것 같아요 !

2024-05-17 08:26 UTC, eunzz6 commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    private Article articleId;
넵 찾아보고 수정해놓겠습니다 !

2024-05-17 08:31 UTC, eunzz6 commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    private LocalDateTime dateCreated;
yyyy-MM-dd 형식으로 해야겠어요 !

2024-05-17 08:32 UTC, eunzz6 commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    @Column(nullable = false, columnDefinition = "BIGINT default 0")
앗 넵 createTable.sql 수정해놓겠습니다 !

2024-05-17 08:37 UTC, eunzz6 commented on src/main/java/com/chatcode/domain/entity/scrap/ScrapId.java
> +}
파일이 두개인것보다 한눈에 보기 쉬울거같아요 ! 수정해놓겠습니다~~!

2024-05-17 08:39 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        LocalDateTime now = LocalDateTime.now();
넵 !~

2024-05-17 08:40 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Avatar avatar = optionalAvatar.orElseThrow(() -> new ContentNotFoundException("Avatar not found"));
참고해서 수정해보겠습니다 ~!!

2024-05-17 08:48 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Avatar avatar = optionalAvatar.orElseThrow(() -> new ContentNotFoundException("Avatar not found"));
오 훨씬 간결해지네욥

2024-05-17 08:54 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Article article = optionalArticle.get();
그렇네요 ! 위처럼 줄였습니다 ㅎㅎ

2024-05-17 08:54 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        }
넵 한번 해보겠습니다 ~!!

2024-05-17 08:55 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +                    Article article = optionalArticle.get();
넵 ~ !! 덕분에 코드가 많이 간결해졌어요 !

2024-05-17 08:56 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +                })
넵, 아직 선호하는 스타일이 없어서 한번 두분 스타일을 보고 따라해보겠습니다 👀

2024-05-17 08:58 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    }
넵 감사합니다 ! LoginUser 정보를 사용해봐야겠어요 ㅎㅎ

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/service/ScrapService.java
> +    public ScrapResponseDTO scrap(Long articleId, Long loginAvatar) {
loginAvatar라는 변수명보다는 Avatar의 ID값임을 명시적으로 표현할 수 있는 변수명이 조금 더 가독성에 좋을 것 같아요

`avtarId`는 어떨까요?

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Avatar avatar = avatarReadRepository.findById(loginAvatar)
Controller단 31L에서 
```Java
ScrapResponseDTO scrapResponseDTO = scrapService.scrap(articleId, user.getAvatar().getId());
```
getAvatar()로 아바타 엔티티만 불러와서 넘겨주면 이 라인은 사용하지 않아도 될것같은데 맞을까요?

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/service/ScrapService.java
> +                .version(0L)
Scarp에 version 필드는 낙관적락을 위해서 존재하는 거여서 0L로 하드코딩 하면 안될 것 같아요!

저도 이번에 처음 접해봐서 사용법은 좀더 알아봐야 할 것 같아요. todo만 남겨두시죠!

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
DTO 클래스명 naming convention이 맞지 않네요! 하나로 통일하면 좋을 것 같아요

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
제가 Valid 어노테이션을 잘 사용해보지 않아서 
PathVariable에 Valid 어노테이션을 달아주게 되면 Valid 어노테이션이 없을때와 어떤 차이점이 있는지 궁금합니다

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +        ScrapResponseDTO scrapResponseDTO = scrapService.scrap(articleId, user.getAvatar().getId());
요기서 user.getAvatar로 아바타 엔티티만 넘겨줘도 서비스 로직이 동작하는데 무리가 없지 않을까 생각이 들었는데 어떻게 생각하시나요? (아래 서비스단 코드에도 코멘트 남겨두었습니다)

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    @GetMapping("/{avatarId}")
스크랩 목록조회이니 `avatars/{avatarId}/scarps`
은 어떠신가요?

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
38Line에는 `@Valid`가 안달려있어서 여쭈어봐요!

2024-05-21 05:54 UTC, minje0204 commented on src/main/java/com/chatcode/service/ScrapService.java
> +                .map(scrap -> ScrapResponseDTO.of(scrap,
scrapList에서 Scrap 엔티티별로 Avatar와 Article에 대한 정보도 들고 있지 않나요?! 이미 조회한 정보를 밑에서 중복 조회하고 있는건 아닌지 생각이 들어서 여쭈어봅니다.

추가로 ScrapResponseDto에서 avatar, article의 ID값만 필요하다면, 필요한 정보들만 select해가는게 보다 효율적일 것 같아요!

2024-05-21 05:56 UTC, minje0204 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
위에 히스토리를 보니 준현님이 추천을 해주셔서 사용하셨나보네요! 준현님께 한번 여쭈어볼게요 ㅎㅎ

2024-05-21 07:06 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +    public ScrapResponseDTO scrap(Long articleId, Long loginAvatar) {
넵 그러는게 좋을 것 같네요 !

2024-05-21 07:38 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +                .version(0L)
넵 알겠습니다 ~!!

2024-05-21 07:40 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
넵 Dto로 변경했습니답!

2024-05-21 07:47 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
Valid 어노테이션은 입력된 데이터의 유효성을 검증하는 걸로 알고 있습니다!
PathVariable에 Valid를 달아주면 널값이 안들어오게 할 수 있어요
그래서 스크랩할때 유효한 article인지 체크하는 용도입니다!
38Line에는 GetMapping으로 단순히 읽는용도라 검증할 필요가 없어서 사용안했습니답!

2024-05-21 07:50 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        Avatar avatar = avatarReadRepository.findById(loginAvatar)
확인해보겠습니다 !!

2024-05-21 07:52 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +        ScrapResponseDTO scrapResponseDTO = scrapService.scrap(articleId, user.getAvatar().getId());
`        Avatar avatar = user.getAvatar();
        ScrapResponseDto scrapResponseDto = scrapService.scrap(articleId, avatar);`
컨트롤러단을 이렇게 수정해보았는데 맞는지 모르겠네욥..!!

2024-05-21 07:53 UTC, eunzz6 commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    @GetMapping("/{avatarId}")
넵 !! 그게 맞을 것 같네요 !!

2024-05-23 06:53 UTC, eunzz6 commented on src/main/java/com/chatcode/domain/entity/scrap/Scrap.java
> +    private LocalDateTime dateCreated;
createDate는 포멧팅을 따로 클래스를 만들어서 설정해야해서, sql문과 localdatetime을 그냥 날짜만 받도록 localdate로 변경했습니다 !

2024-05-24 05:48 UTC, NaMooJoon approved these changes
전반적으로 코드가 훨씬 깔끔해진 것 같아요!

2024-05-24 05:48 UTC, NaMooJoon commented on src/main/java/com/chatcode/service/ScrapService.java
> +        throw new ContentNotFoundException("Scrap not found");
```suggestion
        Scrap scrap = scrapWriteRepository.getReferenceById(articleId);
        scrapWriteRepository.delete(scrap);
```
여기 부분을 조금 짧게 줄여도 괜찮지 않을까 싶네요!
그리고 `findByArticleId` 자체는 직접 DB에서 entity를 조회해오는 거지만, `getReferenceById`는 DB를 조회하지 않고 영속성만 가지고 있는 거라, 실제 내부적으로는 delete by id로 삭제 될 겁니닷!

2024-05-24 05:56 UTC, NaMooJoon commented on src/main/java/com/chatcode/controller/ScrapController.java
> +    public ResponseEntity<BaseResponseDto<ScrapResponseDTO>> scrap(@PathVariable @Valid Long articleId,
클라이언트로 부터 잘못된 타입 또는 값이 들어왔을 때, 컨트롤러 진입 이전에 오류를 검증하는 처리를 스프링에서 제공해주는 검증 방법으로 처리할 수 있어요! 이는 결국 BindingResult를 사용해서 handling 해야 하는데, 

추후에 AOP 방법으로 DTO validation 체킹을 추가할 예정입니다! (ref. #36)

2024-05-24 06:08 UTC, eunzz6 commented on src/main/java/com/chatcode/service/ScrapService.java
> +        throw new ContentNotFoundException("Scrap not found");
앗 넵 !! getReferenceById를 쓰는 습관을 가져봐야겠어요 😂

2024-05-24 07:21 UTC, minje0204 approved these changes
수고하셨습니답

2024-05-24 08:47 UTC, merged